{{- if and (not .Values.yandexCloud.existingSecret) .Values.yandexCloud.iamKeyJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluent-bit.secretName" . }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: {{ .Values.yandexCloud.iamKeyJson }}
{{- end }}
